# Generated by Django 5.1.1 on 2024-09-21 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_cancelbooking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cancelbooking",
            name="booking",
        ),
        migrations.RemoveField(
            model_name="cancelbooking",
            name="user",
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
        migrations.DeleteModel(
            name="CancelBooking",
        ),
    ]
